name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3
  firebase_database: ^3.1.1
  cloud_firestore: ^0.13.0+1
  provider: ^4.0.1
  intl: ^0.15.2
  dropdownfield: ^1.0.3
  string_validator: ^0.1.3
  flutter_rating_bar: ^3.0.0+1
  timeago: ^2.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
